In [18]:
import pandas as pd
import numpy as np
import os

data_dir = '/cosma8/data/do012/dc-he4/analysis'

for lc in range(1728):
    lc00 = f'{lc:04d}'
    # flag filenames
    lcpath = f'{data_dir}/lc{lc00}/'

    files = os.listdir(lcpath)
    for file in files:
        if 'samples_in_lightcone' in file:
            # print(file)
            df = pd.read_csv(os.path.join(lcpath, file))
            df_null_counts = np.sum(df.isnull())
            if (df_null_counts).any():
                print(f'Lightcone {lc00} has at least one empty entry in file {file}.')
    # break

Lightcone 1181 has at least one empty entry in file samples_in_lightcone1181_duplicate_excision_outlier_excision.csv.
Lightcone 1215 has at least one empty entry in file samples_in_lightcone1215_duplicate_excision_outlier_excision.csv.
Lightcone 1215 has at least one empty entry in file samples_in_lightcone1215_duplicate_excision_outlier_excision_scatter_assigned.csv.
Lightcone 1318 has at least one empty entry in file samples_in_lightcone1318_duplicate_excision_outlier_excision_scatter_assigned.csv.
Lightcone 1318 has at least one empty entry in file samples_in_lightcone1318_duplicate_excision_outlier_excision.csv.
Lightcone 1320 has at least one empty entry in file samples_in_lightcone1320_duplicate_excision_outlier_excision_scatter_assigned.csv.
Lightcone 1320 has at least one empty entry in file samples_in_lightcone1320_duplicate_excision_outlier_excision.csv.

## Experiments

In [30]:
df = pd.read_csv('/cosma/home/do012/dc-he4/anisotropy-flamingo/data/analysis/lc1181/samples_in_lightcone1181_duplicate_excision_outlier_excision.csv')

In [20]:
df

,GasMass,LX0InRestframeWithoutRecentAGNHeating,LX0InRestframeWithoutRecentAGNHeatingCoreExcision,LX0WithoutRecentAGNHeating,LX0WithoutRecentAGNHeatingCoreExcision,LX1InRestframeWithoutRecentAGNHeating,LX1InRestframeWithoutRecentAGNHeatingCoreExcision,LX1WithoutRecentAGNHeating,LX1WithoutRecentAGNHeatingCoreExcision,LX2InRestframeWithoutRecentAGNHeating,...,y_lc,y_lc_norot,z_lc,z_lc_norot,3DLcore/Ltot,ObservedRedshift,Flux,ChandraT,GalaxyID,TopLeafID
0,1.503239e+13,3.225882e+44,3.236192e+43,3.679522e+44,3.453848e+43,5.141250e+44,1.589457e+43,5.681952e+44,1.363210e+43,2.256743e+44,...,-107.094047,-159.344392,673.189552,550.362532,0.899680,0.162327,5.014418e-12,2.794964,7.001798e+09,7.001798e+09
1,9.384504e+11,5.251630e+42,1.147802e+42,5.251630e+42,1.147802e+42,1.647088e+41,6.826484e+40,1.647088e+41,6.826484e+40,4.108591e+42,...,-6.402511,-7.776412,40.766295,34.161338,0.781439,0.008712,2.827671e-11,0.563334,5.996957e+09,5.996957e+09
2,7.902740e+12,7.585287e+43,1.917016e+43,7.668063e+43,1.960285e+43,9.744987e+42,6.452762e+42,7.863716e+42,5.653221e+42,6.110370e+43,...,60.527862,-188.280743,296.292636,240.344788,0.747272,0.071499,6.585301e-12,1.961392,1.917102e+10,1.917102e+10
3,6.287832e+12,4.307988e+43,1.136689e+43,4.307988e+43,1.136689e+43,6.715990e+43,3.772029e+42,6.715990e+43,3.772029e+42,3.007463e+43,...,89.024599,12.136710,-170.060732,-123.168250,0.736144,0.044209,9.714461e-12,1.954560,1.559483e+10,1.559483e+10
4,6.614250e+12,4.221574e+43,1.424123e+43,4.251674e+43,1.461748e+43,7.534493e+42,5.465094e+42,6.480981e+42,4.881900e+42,3.070235e+43,...,21.369836,49.741511,211.888494,240.397288,0.662656,0.057990,5.476997e-12,2.129582,1.978836e+09,1.978836e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,1.116004e+14,5.610705e+44,5.508364e+44,5.911708e+44,5.797327e+44,5.875588e+44,5.755186e+44,5.875588e+44,5.755186e+44,3.876925e+44,...,123.625876,278.031457,-492.573569,-313.783367,0.018240,0.120996,1.643247e-11,8.360359,6.293553e+07,6.293560e+07
814,1.382980e+13,4.770905e+43,4.688129e+43,4.913882e+43,4.831106e+43,2.411790e+43,2.355352e+43,2.246238e+43,2.197325e+43,3.284700e+43,...,142.097058,187.856902,-140.851152,4.225590,0.017350,0.056806,6.188349e-12,2.841188,1.160329e+10,1.160329e+10
815,1.051408e+13,3.281792e+43,3.241151e+43,3.281792e+43,3.241151e+43,1.470710e+43,1.450390e+43,1.470710e+43,1.450390e+43,2.255597e+43,...,4.555739,-1.437142,76.805717,77.435138,0.012384,0.017948,4.376273e-11,2.477314,1.484095e+10,1.484095e+10
816,2.778844e+12,4.375300e+42,4.324498e+42,4.375300e+42,4.324498e+42,1.173203e+42,1.154152e+42,1.173203e+42,1.154152e+42,3.025879e+42,...,17.962448,2.736559,-52.481727,-42.707681,0.011611,0.013897,1.217947e-11,1.606427,7.160288e+09,7.160288e+09
817,1.657857e+13,5.967394e+43,5.929768e+43,6.170571e+43,6.132946e+43,3.235787e+43,3.213212e+43,3.017560e+43,2.994985e+43,4.116222e+43,...,65.526999,-184.530964,296.474134,244.361427,0.006305,0.071664,5.167357e-12,3.066354,6.195786e+09,6.195786e+09

In [21]:
df[df.isnull()]

,GasMass,LX0InRestframeWithoutRecentAGNHeating,LX0InRestframeWithoutRecentAGNHeatingCoreExcision,LX0WithoutRecentAGNHeating,LX0WithoutRecentAGNHeatingCoreExcision,LX1InRestframeWithoutRecentAGNHeating,LX1InRestframeWithoutRecentAGNHeatingCoreExcision,LX1WithoutRecentAGNHeating,LX1WithoutRecentAGNHeatingCoreExcision,LX2InRestframeWithoutRecentAGNHeating,...,y_lc,y_lc_norot,z_lc,z_lc_norot,3DLcore/Ltot,ObservedRedshift,Flux,ChandraT,GalaxyID,TopLeafID
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
817,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Get rows that contain at least one null value
df[df.isnull().any(axis=1)]

,GasMass,LX0InRestframeWithoutRecentAGNHeating,LX0InRestframeWithoutRecentAGNHeatingCoreExcision,LX0WithoutRecentAGNHeating,LX0WithoutRecentAGNHeatingCoreExcision,LX1InRestframeWithoutRecentAGNHeating,LX1InRestframeWithoutRecentAGNHeatingCoreExcision,LX1WithoutRecentAGNHeating,LX1WithoutRecentAGNHeatingCoreExcision,LX2InRestframeWithoutRecentAGNHeating,...,y_lc,y_lc_norot,z_lc,z_lc_norot,3DLcore/Ltot,ObservedRedshift,Flux,ChandraT,GalaxyID,TopLeafID
804,3.081448e+42,1.216702e+43,1.308145e+43,1.216702e+43,4.534055e+42,4.197494e+42,4.534055e+42,4.197494e+42,9.004609e+42,8.318785e+42,...,-98.128792,62.944596,53.028528,0.069903,0.027902,8.197850e-12,2.064185,1.656472e+10,1.656472e+10,NaN

In [33]:
# Get rows that contain at least one null value
df[df.isnull().any(axis=1)]['GalaxyID'].values[0]

16564717640.0

In [34]:
df0 = pd.read_csv('/cosma/home/do012/dc-he4/anisotropy-flamingo/data/analysis/lc1181/samples_in_lightcone1181_duplicate_excision.csv')

In [36]:
df0[df0['GalaxyID'] == 16564717640]

Empty DataFrame
Columns: [GasMass, LX0InRestframeWithoutRecentAGNHeating, LX0InRestframeWithoutRecentAGNHeatingCoreExcision, LX0WithoutRecentAGNHeating, LX0WithoutRecentAGNHeatingCoreExcision, LX1InRestframeWithoutRecentAGNHeating, LX1InRestframeWithoutRecentAGNHeatingCoreExcision, LX1WithoutRecentAGNHeating, LX1WithoutRecentAGNHeatingCoreExcision, LX2InRestframeWithoutRecentAGNHeating, LX2InRestframeWithoutRecentAGNHeatingCoreExcision, LX2WithoutRecentAGNHeating, LX2WithoutRecentAGNHeatingCoreExcision, M500, SOAPID, SpectroscopicLikeTemperatureWithoutRecentAGNHeatingCoreExcision, Vx, Vy, Vz, Y5R500WithoutRecentAGNHeating, phi_on_lc, phi_on_lc_norot, redshift, snap_num, theta_on_lc, theta_on_lc_norot, x_lc, x_lc_norot, y_lc, y_lc_norot, z_lc, z_lc_norot, 3DLcore/Ltot, ObservedRedshift, Flux, ChandraT, GalaxyID, TopLeafID]
Index: []

[0 rows x 38 columns]